// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Textblock from './Textblock';

export {
	Hero,
	Textblock,
};

export const components = {
	hero: Hero,
	textblock: Textblock,
};
